# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1


WORKDIR /api

COPY package*.json .
RUN bun install

COPY . .

# run the app
USER bun
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "--watch", "run", "index.ts" ]